### ISSUE TITLE
make_trackhubs fails to recognize a file with multiple library types

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#13]
In my tests, it seems to just pick one of the library types and lump stuff under that. 

It should understand and handle them.

**Comment by nsheff** [comment]
@cdietzgit Charles will you be able to fix these make_trackhubs issues before the pending merge?

**Comment by afrendeiro** [comment]
make_trackhubs is deprecated, feel free to close the issue if there are no other implications.
