### ISSUE TITLE
Connecting sample and project

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#150]
From @afrendeiro  #144 
>  Can we reverse the removal of Sample-Project linking? It is true these don't need to exist, and probably shouldn't be used in the looper workflow but are extremely useful outside of it.

Further discussion:

> vreuter: I'll address the other points separately, but I want to first focus on the samples/project deal. Why is that good/desirable? I see value in a sample knowing about certain attributes of a project that are sample-independent, but it would be bizarre for a sample to know about other samples via a project, especially with inter-sample independence advertised as a bedrock looper principle. I think it'd be good to facilitate access by each sample to a subset of project metadata, but I strongly oppose the existence of a direct reference of a sample to its project. Imports, function calls, object references -- I think circular is bad.

> nsheff: Sample/Project link: I see both sides. I don't have strong feelings at this point. I think if you have a sample, you probably got it through a project, so why do you need the pointer? Just remember where you pulled the sample. But @afrendeiro if you can give a specific use case for when you'd have a Sample, need its Project, and not have accessed the sample through that Project in the first place (necessitating a link to Project from Sample), that would be interesting.

> afrendeiro: Well I generally don't ask for features if I'm not using them:
My case is in when running a pipeline. Imagine your pipeline could make use of a few project-centric variables like a specific directory where you want to group a certain type of output for all samples (e.g. bigwig files, some pdfs, etc - this is not the norm for all of the sample's output but just one or two). This variable is common to all samples of the project and could simply be defined by extending the project's config with it. Instead of always having this passed as a parameter, one could simply read the sample's config (which is the only thing I require as input) and get that variable though the project's.
I do agree though that there must be a way to contain circularity and recursiveness specially in the serialization of the objects to yaml (I believe something was/is in place to assure this), so yes it is not straightforward to do this out of the box - it would be good if possible though.

**Comment by vreuter** [comment]
Verdict?

**Comment by nsheff** [comment]
To me there is no verdict yet...

**Comment by afrendeiro** [comment]
Well, I'd be willing to meet you half way and have only access to the projects first-level attributes, but I also see Nathan's point.
Maybe we can leave it as-is for this release and keep thinking more about this. I'm curious about what other people that are/will be using mostly the models would say.

**Comment by vreuter** [comment]
I'm good with the current level of connection; `Sample` has access to `metadata`, `derived_columns`, `implied_columns`, and `trackhubs`, so I'm good with closing this if others are?

**Comment by nsheff** [comment]
Hey @vreuter with all the new attmap stuff, do you think this has been generally addressed? it seems that the attmap attribute filters concept has sort of made it possible to handle this pretty well while keeping the connection, am I right? if so maybe this can be closed?

**Comment by vreuter** [comment]
I see no value in it, but c'est la vie--it's there. https://github.com/pepkit/peppy/issues/315
