### ISSUE TITLE
Parsing a sample_annotation.csv file with mac line endings

### ISSUE THREAD

**Issue by olhakholod** [pepkit/peppy#154]
While running looper with run option I got a following error:

Traceback (most recent call last):
  File "/home/okbm4/.local/bin/looper", line 12, in <module>
    load_entry_point('looper==0.6.0rc3', 'console_scripts', 'looper')()
  File "/home/okbm4/.local/lib/python2.7/site-packages/looper/looper.py", line 842, in main
    compute_env_file=getattr(args, 'env', None))
  File "/home/okbm4/.local/lib/python2.7/site-packages/looper/loodels.py", line 29, in __init__
    no_compute_exception=RuntimeError, **kwargs)
  File "/home/okbm4/.local/lib/python2.7/site-packages/looper/models.py", line 666, in __init__
    self.sheet = check_sheet(path_anns_file)
  File "/home/okbm4/.local/lib/python2.7/site-packages/looper/models.py", line 110, in check_sheet
    index_col=False, engine="python")
  File "/home/okbm4/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/okbm4/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/okbm4/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "/home/okbm4/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 995, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/home/okbm4/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1989, in __init__
    self._make_reader(f)
  File "/home/okbm4/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 2119, in _make_reader
    dialect=dia)))
_csv.Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?

This error is coming from annotation file endings:

[okbm4@aphrodite metadata]$ cat microtest.csv 
Sample_1,sample5,RNA-seq,human,blast_cell,1,source1[okbm4@aphrodite metadata]$

We can fix it with the following command:

[okbm4@aphrodite metadata]$ sed 's/\r/\n/g' microtest.csv > microtest2.csv
[okbm4@aphrodite metadata]$ cat microtest2.csv 
folder_name,sample_name,library,organism,cell_type,time_point,data_source
Sample_1,sample1,RNA-seq,human,blast_cell,2,source1
Sample_2,sample2,RNA-seq,human,blast_cell,3,source1
Sample_3,sample3,RNA-seq,human,blast_cell,4,source1
Sample_4,sample4,RNA-seq,human,blast_cell,5,source1
Sample_5,sample5,RNA-seq,human,blast_cell,1,source1

Thus, looper run without error.

**Comment by nsheff** [comment]
The issue here is with mac-generated line endings, which looper does not understand.

I wonder if this will continue to creep up and we should put in either one of these solutions:

1. detect mac line endings and understand them.
2. detect mac line endings and provide an understandable error.

**Comment by vreuter** [comment]
*comes in with unsolicited (albeit tepid) opinion*...I'd be in slight favor of supporting the line endings. I think it could lower the entry barrier (...*and a cliche!*) and encourage broader adoption. It also makes some sense as there's the Mac-directed instruction about `PATH` alteration post-installation in the docs, right?

**Comment by vreuter** [comment]
That said, this [blast from the past](https://www.youtube.com/watch?v=ks-N4rI_1RU) feels about right for this sort of thing...

**Comment by nsheff** [comment]
The reason to go for the second I I think is to just solve the problem once and for all... if we do the first, we have to make all software that is PEP project compatible convert mac line endings.

**Comment by michalstolarczyk** [comment]
I think that the problem here is related to MS Excel which was used to generate the CSV file. It produces the `CR LF` line endings. The `CR` use was eliminated with release of macOS (which was 17 years ago). Consequently, if the CSV is created in e.g. TextEdit on Mac, then the `LF` is used. 

However, I've been using MS Excel-generated CSV files in `peppy` and didn't get related errors. So maybe this issue is resolved?

**Comment by vreuter** [comment]
Yeah that's definitely possible. We used to have the `pandas` call for parsing be `read_csv` and switched at one point to `read_table`. That may have done it, or one of the more recent `pandas` versions may have changed the course of action taken when no `lineterminator` argument is explicitly provided.

**Comment by nsheff** [comment]
Ok let's close this then for now.
