### ISSUE TITLE
Interest to support JSON?

### ISSUE THREAD

**Issue by vreuter** [pepkit/peppy#206]
I tend to have a bit more trouble writing/getting correct parse from YAML than from JSON. Is there any interest to additionally support JSON files in places where YAML is currently supported? A *minor* additional win to that capability in and of itself would be the ability to remove the *dependency* on an external package (i.e., `PyYAML`). Admittedly, though, as mentioned that feels small since many users are likely to already have that installed.

**Comment by nsheff** [comment]
In theory I have no problem with it; I personally find yaml much easier to read (and write) than JSON...which files exactly do you want to use in JSON format, out of curiosity?

I suppose the solution is just to write a basic function (if one doesn't already exist) that accepts either JSON or yaml, and swap that out for all the places we use `yaml.load`... then it would just seemly accept either, in any combination.

This function should probably live in `peppy`. So, I'm open.

**Comment by vreuter** [comment]
I think probably not worth it, so I'm going to close for now. My *perception* is that I more frequently run into parsing errors with YAML, but I think that it's a volume thing rather than frequency--I've just used more YAML.

**Comment by nsheff** [comment]
Ok. I don't think it would be hard to do, so we could rethink if you find yourself wanting JSON more.
