### ISSUE TITLE
Using peppy's logger

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#216]
How can you set the logger verbosity interactively? I can't find any docs on this.

I tried:

```
import peppy
peppy._LOGGER.setLevel(5)
```

but I can't get it be more verbose.

**Comment by vreuter** [comment]
Modifying configuration in interactive context tends to be struggle-fraught, or at least has seemed so in the past. What happens if, after you invoke that, you do `peppy._LOGGER.getEffectiveLevel()`?

**Comment by nsheff** [comment]
it correctly yields `5`.

How you typically get a verbose logger in an interactive session?

**Comment by vreuter** [comment]
OK cool.
I'm not sure if I've tried that. What about something like this:
```
import peppy
peppy.setup_peppy_logger(5, "testing.log")
```

**Comment by nsheff** [comment]
Yep. that works. thanks. and if I don't want it to go any file, but just log to screen?

**Comment by vreuter** [comment]
The filename's optional; the messages should be sent to `stdout` regardless.

**Comment by nsheff** [comment]
perfect. thanks.
