### ISSUE TITLE
default derived attributes/columns (data_source) not needed?

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/peppy#219]
- the default derived column (`data_source`) will not be announced in the [docs](https://peppy.readthedocs.io/en/latest/derived-columns.html)/[pepkit website](https://pepkit.github.io/docs/derived_columns/) anymore, but the functionality will be temporarily kept in PEP to support the older projects,
- the derived/implied columns will be referred to as derived/implied attributes in future versions, but they will be backwards compatible

**Comment by nsheff** [comment]
what exactly is the action item here?
