### ISSUE TITLE
Does peppy implement project constants?

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#220]
@michalstolarczyk implemented `constants` in `pepr`, but this is not documented for peppy:

http://code.databio.org/pepr/articles/feature_constants.html

Does peppy also do this? Should we document it on the website?

**Comment by nsheff** [comment]
actually now that I think about it, can't this be accomplished by just setting a derived attribute with no 
variables? do we need a separate thing called `constants` (which I guess should be `constant_attributes`?)

**Comment by nsheff** [comment]
Ok, thinking more deeply... they are different, because they don't have to exist in the annotation file; they are added. So they are more like implied attributes. so, you could make an implied attribute that didn't depend on any other attribute, that could be a constant attribute.

I think it's sufficiently different to be it's own concept. SO I think we need to rename the section to `constant_attributes` (for both `peppy` and `pepr`), and document this on the pepkit web page.

Any other comments?

**Comment by michalstolarczyk** [comment]
Changed `constants` to `constantAttributes` in https://github.com/pepkit/pepr/commit/24092bec2a43f374a98f1cdbab724d957cce4135

**Comment by vreuter** [comment]
Right now the [documentation is here](https://peppy.readthedocs.io/en/latest/define-your-project.html#project-config-section-constants)
And there's an [attribute docstring](https://peppy.readthedocs.io/en/latest/api.html#peppy.Project.constants) on `Project`. In addition to package source code itself I think those are where changes would need to be made, along with perhaps in tests.

**Comment by nsheff** [comment]
Interesting -- that link is not even accessible from the table of contents. It should also be removed completely as it's been superseded by the pepkit website.

thanks for pointing this out.

**Comment by vreuter** [comment]
Closing for https://github.com/pepkit/peppy/issues/222 to get task tracking on main issues page without editing opening comment here and having more confusing logic flow

**Comment by nsheff** [comment]
thanks.
