### ISSUE TITLE
CommandChecker class

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#221]
Is the `CommandChecker` class actually used anywhere, either in `peppy` or outside it?

I wonder if this is the right place for it. Might it be more useful in `pypiper` ?

**Comment by nsheff** [comment]
actually the real value is just the `is_command_callable` function

**Comment by nsheff** [comment]
@vreuter this seems like something that should go into ubiquerg then... (the `is_command_callable` function) -- yes?

**Comment by vreuter** [comment]
I've not used it anywhere, and I haven't seen a usage. Your suggestion sounds good.
