### ISSUE TITLE
Revising peppy constant_attributes implementation

### ISSUE THREAD

**Issue by vreuter** [pepkit/peppy#222]
From @nsheff , to address #220 
- [ ] rename `constants` section to `constant_attributes` in `peppy` implementation (and attribute docstring)
- [ ] move `constants` documentation from outdated `peppy` page to pepkit website
- [ ] remove inaccessible documentation from `peppy` readthedocs site

**Comment by stolarczyk** [comment]
switched to `sample_modifiers.append`
