### ISSUE TITLE
cryptic error: unmatched regex-like

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#223]
From https://github.com/pepkit/looper/issues/53

- [ ] `Unmatched regex-like` should be downgraded to `debug`.
- [ ] And change it to something like "wildcard file pointer did not match any files for sample 'X'".

**Comment by nsheff** [comment]
@vreuter did this already get changed? I can't find that text anywhere so I'm thinking this is solved?

**Comment by vreuter** [comment]
https://github.com/pepkit/looper/issues/53#issuecomment-471973168

**Comment by nsheff** [comment]
wow, nice find!
