### ISSUE TITLE
Refresh samples after subproject activation

### ISSUE THREAD

**Issue by vreuter** [pepkit/peppy#233]
#229

**Comment by nsheff** [comment]
do you think this complexity means we should just bag the "keep any changes" thing, and simple restart the project with the `activate_subproject` function?

**Comment by vreuter** [comment]
https://github.com/pepkit/peppy/pull/232#issuecomment-442608771

**Comment by vreuter** [comment]
I don't have a preference really about the "keep user changes;" I think you and @afrendeiro may have a better feel for how important that is. I don't think this would be super tricky, but if you're leaning to the "overwrite-all" option anyway, and you want to avoid _any_ additional development-side complexity, that sounds good, too.

**Comment by nsheff** [comment]
Ok, agreed.

**Comment by vreuter** [comment]
Done with https://github.com/pepkit/peppy/pull/232/commits/40c7775c28cae3b30cb2dcae163a8176c5f26877

**Comment by nsheff** [comment]
@vreuter is this issue to be closed?

**Comment by vreuter** [comment]
Yeah there are more recent relevant tickets that cover the same idea.
