### ISSUE TITLE
Add pep attributes/properties to documentation

### ISSUE THREAD

**Issue by aaron-gu** [pepkit/peppy#234]
As a user browsing the peppy documentation for the first time to see how to access the sample annotation sheet from the pep object, I could not find what I wanted. @vreuter Nathan mentioned in lab meeting today that you might have an easy fix to include the pep attributes in the documentation?

**Comment by vreuter** [comment]
Sorry you had to wander around the docs. The `sheet` attribute should show up now in the main docs API under `Project` once the commit referenced here is merged in. This works for me now when I build them locally. In the meantime, if you want to test it out, to render locally you can `cd` from the repo root into `doc` and then `build html` as long as you have `sphinx` installed. Then you can view with something like `firefox build/html/index.html` and navigate from there in the browser.
