### ISSUE TITLE
Remove default_compute?

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#237]
What is the difference between the `default_compute` and `compute_env_file` arguments to the `peppy.Project` constructor?

**Comment by nsheff** [comment]
I think I see.. `default_compute` is the yaml file for the default, embedded settings

`compute_env_file` is meant to be the user-specified one.

It's slightly confusing that `default_compute` is an argument to the constructor though, and I feel the names aren't very parallel.

**Comment by vreuter** [comment]
Can we just remove it at the source, in `peppy` itself? I think it's of sufficiently infrequent use that the benefit of removing the ambiguity is worth the slight loss of flexibility. If an individual or a group using a `Project` wants to change that, they could just extend it and override `default_compute_envfile` to get the same effect.

**Comment by nsheff** [comment]
got it!. 

of course -- divvy is going to eventually replace lots of stuff in peppy. the point is just that I'm restructuring things a bit in divvy. then peppy will just be adapted to use it. so all this will end up getting removed from peppy.

**Comment by nsheff** [comment]
will be resolved with #244
