### ISSUE TITLE
Use mkdocs

### ISSUE THREAD

**Issue by vreuter** [pepkit/peppy#240]
Repo for theme: https://github.com/databio/mkdocs-databio/
The theme should be used here, per https://github.com/databio/mkdocs-databio/issues/5
Any Jupyter notebooks used as example-based documentation should be included, as should API docs.
- [x] Support
- [x] Contributing
- [x] Changelog
- [x] API
- [x] Notebooks

**Comment by vreuter** [comment]
I know less about the notebook docs than API, though I have gotten no errors when I've built the docs so this can probably be closed. @nsheff are the notebook builds how you want them?

**Comment by nsheff** [comment]
Yep, notebooks are rendering correctly. thanks!
