### ISSUE TITLE
Switch to divvy for computing configuration

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#244]
I have now pulled out the computing environment (PEPENV) stuff into a new package called `divvy`.

As soon as `divvy` is released, we should adapt `peppy` to use `divvy`.

The release of divvy will happen after we finish this: https://github.com/databio/divvy/issues/4

**Comment by nsheff** [comment]
This issue is basically a more polished version of https://github.com/pepkit/looper/issues/59

**Comment by nsheff** [comment]
In the process we want to keep in mind this: https://github.com/pepkit/looper/issues/54

**Comment by michalstolarczyk** [comment]
Do we also change to `COMPUTE_SETTINGS_VARNAME = "DIVCFG"` but keep `PEPENV` to retain backwards compatibility?

**Comment by nsheff** [comment]
yes.

**Comment by nsheff** [comment]
@michalstolarczyk is this complete?

**Comment by michalstolarczyk** [comment]
Yes. I did not close it since I wanted to confirm it works with `peppy` at its final release stage.

**Comment by michalstolarczyk** [comment]
.. and with `divvy` when it's finally released

**Comment by nsheff** [comment]
got it!
