### ISSUE TITLE
More generic selection for samples

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/peppy#245]
Currently we can use the `protocol` sample attribute to select for the samples of interest using the `fetch_samples` function.

Could we make the selection more generic, i.e., use any user-supplied sample attribute for that?

This would imply changes in the looper interface (`--exclude/include-protocols` option) which is where I am coming from.

**Comment by michalstolarczyk** [comment]
I've added additional parameter `attribute` to select the sample attribute the inclusion/exclusion is based on and set its default value to `protocol`, so everything should work fine. Will need to edit the related unit tests.

**Comment by nsheff** [comment]
I'm not sure `attribute` is the best name for this... maybe `toggling-attribute`?

I think we should brainstorm a bit about the best name for both the attribute option name and the inclusion/exclusion option names.

**Comment by vreuter** [comment]
What about `selector`? To me at least "toggling" sounds like it could be strictly to activate or deactivate something to *run*. Even if that's the main use case for this right now, we intend for the implementation to allow selection of a subset of samples for an arbitrary reason, right?

**Comment by michalstolarczyk** [comment]
When I was introducing the changes to the function I wanted to name this parameter `selection_attribute` or `filter_attribute` but eventually I went with shorter version. And that's right, the name should be more descriptive. This is especially relevant when the changes will be propagated to `looper` and `caravel` interfaces.

I like `selection_attribute` and `selector` the most

**Comment by nsheff** [comment]
I would vote for `selector-attribute`... and then it would be `selector-exclude` and `selector-include` for the filter values.

**Comment by michalstolarczyk** [comment]
Ok, seems right. I'll change it to this set of attributes here and in `looper`
