### ISSUE TITLE
implied_columns no longer working

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#253]
Maybe related to https://github.com/pepkit/looper/issues/60
if you use `implied_columns` you get:

```
utils:247 (grab_project_data) [DEBUG] > Project lacks section 'implied_attributes', skipping 
```

we should retain backwards compatibility.

**Comment by michalstolarczyk** [comment]
This small change solved this for me on `dev`. Feel free to revert if you wanted to do it differently.

**Comment by vreuter** [comment]
What does "do not work" mean?

**Comment by michalstolarczyk** [comment]
The attributes are not set then

**Comment by michalstolarczyk** [comment]
Ok, it looks like it's working for both now when using both `attmap` and `peppy` on `dev`
