### ISSUE TITLE
selector attribute can't be empty

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#256]
if you pass `None` you get:

```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 707, in main
    run = Runner(prj)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 60, in __init__
    self.counter = LooperCounter(len(prj.samples))
  File "/home/ns5bc/.local/lib/python2.7/site-packages/peppy/project.py", line 99, in __getattr__
    self.prj, selector_attribute=self.attribute, selector_include=self.include, selector_exclude=self.exclude)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/peppy/utils.py", line 186, in fetch_samples
    if proj.samples and not any([hasattr(i, selector_attribute) for i in proj.samples]):
TypeError: hasattr(): attribute name must be string
```

**Comment by nsheff** [comment]
this is problematic because the looper default is set to `None`.

See #245.

**Comment by michalstolarczyk** [comment]
So do we remove the `selector_attribute="protocol"` default in `peppy` (as discussed here: https://github.com/pepkit/peppy/commit/14e3957621aa35f98b603eacec8ae9932b34d23c#r32291286) and throw an error if it's called with `selector_attribute=None`?

**Comment by nsheff** [comment]
I think it's not an *error* if `selector_attribute-None` -- it just doesn't select anything.

Yes, I think we remove the default in peppy -- and I think we add that default in at the looper stage instead. peppy should default to `None` though, as @vreuter suggested

**Comment by michalstolarczyk** [comment]
> it just doesn't select anything.

Meaning no "filtration" occurs?

**Comment by michalstolarczyk** [comment]
Need to change unit tests accordingly

**Comment by nsheff** [comment]
yes.
