### ISSUE TITLE
derived_columns no longer working

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#258]
Same as https://github.com/pepkit/peppy/issues/253 but for `derived_columns`

**Comment by vreuter** [comment]
Can you provide a log or traceback? They should've both failed for the same reason before https://github.com/pepkit/peppy/commit/dd8c8dc89ac0aca33a4049edae0a3fab6c7cb944 and be fixed for the same reason afterward. Is `implied_columns` behaving the same?

**Comment by nsheff** [comment]
I'm not sure because I had changed it to use 'implied_attributes' in my test...the traceback is unrelated, it's just caused by a 'file not found' or something. 

but what happens if you use `implied_columns` instead of `implied_attributes` is that you never hit these debug lines:

```
sample:532 (set_file_paths) [DEBUG] > Deriving column for Sample 'NBM13_CD34': 'read2' 
sample:538 (set_file_paths) [DEBUG] > Setting 'read2_key' to 'FGB_R2' 
```

so `read2`stays set as `FGB_R2`

it's like it doesn't recognize that config file section at all. I think it only derives the default `data_source` attribute.

**Comment by michalstolarczyk** [comment]
works with `peppy` and `attmap` on `dev` branches
