### ISSUE TITLE
tutorials hard-code personal locations

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#268]
@michalstolarczyk 

It would be good if the jupyter notebooks can be rendered by anyone, which means we can't put things like this in them:

```
os.chdir("/Users/mstolarczyk/Uczelnia/UVA/")
```

can you think of another way to accomplish what you need in the notebook so that I can render them if I need to?

**Comment by michalstolarczyk** [comment]
We can follow pepr and pull the example_peps repository to the examples directory here and then use them in the notebooks with relative paths.

**Comment by nsheff** [comment]
sounds good to me.
