### ISSUE TITLE
coverage badge

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#271]
dev branch has a coverage badge pointing to @vreuter space -- 

https://coveralls.io/github/vreuter/peppy?branch=master

can we:

- make this a centralized link (the way we're doing with travis?) (as in, use the org space instead of personal space?
- the badge says 'unknown' so it's not populating can we either fix that or remove it?

**Comment by vreuter** [comment]
OK, I requested `coveralls` access for `pepkit`, so I think that request will send you an email

**Comment by nsheff** [comment]
granted.

**Comment by vreuter** [comment]
:ok_hand:
