### ISSUE TITLE
Transitioning to major version

### ISSUE THREAD

**Issue by vreuter** [pepkit/peppy#272]
- [ ] remove temp patches for `looper` backcompat (https://github.com/pepkit/peppy/pull/260/commits/a0324041b9c2ce5e0ea8e917b2543f66b8852d43)
  - [ ] imports in `__init__.py` of a couple `attmap` classes; remove these to force import directly from `attmap`.
  - [ ] declaration of `COMPUTE_SETTINGS_VARNAME` in `__init__.py`; remove and instead force import from `divvy`
  - [ ] Old `alpha_cased` function that's no longer needed
- [ ] remove support for previous names (e.g., `library` (done?), `implied_columns`, `implied_attributes`, `compute`)
- [ ] remove Python 2 support (?) and require 3.5

**Comment by khoroshevskyi** [comment]
Python 2 support was removed, all other issues were closed, closing this issue
