### ISSUE TITLE
attribute naming for sample sheet

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#280]
_Raised by @johanneskoester in https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/pull/6/files_

Why is the sample dataframe called sheet and the subannotation called sample_subannotation. Seems to be asymmetric. Why not calling the first samples and the second sample_subannotation?

thoughts @afrendeiro ?

**Comment by vreuter** [comment]
What would you rename what's currently called `samples`?

**Comment by nsheff** [comment]
I wouldn't rename `samples`... I do think we're inconsistent though. 

I think `sheet` is the actual pandas data table; 
`samples` is the list of `Sample` objects, 
`sample_subannotation` is what?

and what's the equivalent of the actual pandas data table for `sheet` ? should it be `subannotation_sheet` or `subsheet`? 

This is what I'm thinking... just standardizing the names. I'd have to dig into it for the details

**Comment by vreuter** [comment]
Yeah it should be called `subsheet`

**Comment by vreuter** [comment]
`subsamples` doesn't (and I don't think should) exist on a `Project`; it exists on a `Sample`, though.

**Comment by vreuter** [comment]
So we're already // w.r.t. objects (`samples` on `Project` and `subsamples` on `Sample`) and could be so w.r.t. tables also by switching to `subsheet`. That seems most reasonable to me.

**Comment by afrendeiro** [comment]
I agree with @vreuter, the logical seems to rename `sample_subannotation` to `subsheet`.

The other option would be to keep `sample_subannotation` and rename `sheet` to `sample_annotation` to match config - this would be a bit more explicit where things come from but more likely to break backward-compatibility with older projects.

**Comment by nsheff** [comment]
I actually like the explicit way better... I never really liked `.sheet` personally, and never used it. we could keep it unadvertised for backwards compatibility if it was worth the public-facing name change for clarity.

The other possibility is: `sample_sheet` and `subsample_sheet`. or (better?) `sample_table` and `subsample_table`.

I think if I were starting now, I'd say `sample_table` and `subsample_table` are the best balance of conciseness and expressiveness. Whether that's worth the change is depatable.

@johanneskoester do you have an opinion?

**Comment by michalstolarczyk** [comment]
> * `Project.samples` is the list of `Sample` objects
> * `Sample.subsamples` is the list of `Subsample` objects
> * `Project.subsample_table` is the pandas data.table of subsamples
> * `Project.sample_table` is the pandas data.table of samples

Yes, I like how clear this is.

Are we planning to incorporate these changes (and other snakemake integration code) in the [v0.20](https://github.com/pepkit/peppy/pull/260) or as a part of the next bigger one which may include non backwards compatible changes in pepkit?

**Comment by vreuter** [comment]
> I actually like the explicit way better... I never really liked `.sheet` personally, and never used it. we could keep it unadvertised for backwards compatibility if it was worth the public-facing name change for clarity.

I've also not used these so only personal preference is for parallelism, not for any specific name. I think when the change is made we should remove `sheet` and not support it. 

> Does `Sample.subsample_table` exist as the subset of subannotations belonging to a sample? Probably not necessary...

I think not, only `subsamples` that gives the objects

**Comment by johanneskoester** [comment]
>     * `Project.samples` is the list of `Sample` objects
>     * `Sample.subsamples` is the list of `Subsample` objects
>     * `Project.subsample_table` is the pandas data.table of subsamples
>     * `Project.sample_table` is the pandas data.table of samples
That looks good to me.

**Comment by nsheff** [comment]
Ok, let's go with that

> Are we planning to incorporate these changes (and other snakemake integration code) in the v0.20 or as a part of the next bigger one which may include non backwards compatible changes in pepkit?

This is not a major change, let's incorporate in 0.20. Plus, these sample subannotation changes are all new in 0.20 anyway, so better to do it now.

>  I think when the change is made we should remove sheet and not support it.

That's fine with me, but @afrendeiro has almost certainly been using `.sheet` widespread in his stuff (since he created it), so it's a little inconsiderate...I don't see why we wouldn't just allow `.sheet` to silently point so that he doesn't have to redo all his old stuff to keep it functional. It's not like it's hard to implement. But if OK with @afrendeiro then I say we drop the old way.

**Comment by vreuter** [comment]
> > I think when the change is made we should remove sheet and not support it.
> 
> That's fine with me, but @afrendeiro has almost certainly been using `.sheet` widespread in his stuff (since he created it), so it's a little inconsiderate...I don't see why we wouldn't just allow `.sheet` to silently point so that he doesn't have to redo all his old stuff to keep it functional. It's not like it's hard to implement. But if OK with @afrendeiro then I say we drop the old way.

This makes sense if we schedule an actual removal of it. Right now we have lots of code devoted to supporting old API versions, with no plan to actually remove them.

**Comment by nsheff** [comment]
I know what you mean -- you're just thinking of it from the developer perspective and I'm thinking from the user perspective :smile:. let's let @afrendeiro decide.

**Comment by vreuter** [comment]
OK. Here we're actually in better shape than in analogous situations previously--`sheet` is already read-only--so I'm fine w/ not even scheduling a removal for this one. The only concern then is reservation of a relatively high-value name (`sheet` -- short, common, versatile) and the associated encroachment on the flexibility of a project config (someone can't have a `sheet` key arbitrarily added then). I think that's not a huge deal and restoring that flexibility right now, with a relatively small user base, isn't as valuable as avoiding the imposition on @afrendeiro , but it's something to consider as user count inreases.

**Comment by afrendeiro** [comment]
> * `Project.samples` is the list of `Sample` objects
> * `Sample.subsamples` is the list of `Subsample` objects
> * `Project.subsample_table` is the pandas data.table of subsamples
> * `Project.sample_table` is the pandas data.table of samples

^^ This is fine with me too - better to standardize now.
