### ISSUE TITLE
Prettify project repr

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#290]
Right now if you create a project and then view it, you get a massive blob of meaninglessness... we should improve the way it's represented to the user interactively.

@afrendeiro this seems like something up your alley...

**Comment by vreuter** [comment]
An itemized list of desired attributes for display would be helpful; it's difficult to guess what's desired since projects have much (and arbitrary) data.

**Comment by vreuter** [comment]
Also it'd be nice to not need to do this multiple times, and by simple number of possible combinations of attributes (even restricting to a "reasonable" subset of the standard ones) without suggestion/confirmation of a list immediate consensus even among 2 people seems improbable.

**Comment by vreuter** [comment]
See https://github.com/pepkit/peppy/issues/296

**Comment by afrendeiro** [comment]
Personally, I would prefer something with at most 4-5 lines: some sort of `name` (as in some of the https://github.com/pepkit/example_peps and most PEPs I make), and a count of samples per `protocol` would suffice.

I have done something like that for the master class of my library which build on a PEP: https://github.com/afrendeiro/toolkit/blob/dev/ngs_toolkit/analysis.py#L203
(and informally, some pretifying for peppy.Sample objects too https://github.com/afrendeiro/toolkit/blob/dev/ngs_toolkit/analysis.py#L224).
