### ISSUE TITLE
contstants in subprojects are ignored

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#292]
if I define a project with `constants`, and then add some `constants` in a subproject, when I activate that subproject, the constants are not available.

Therefore, somehow, constants are being treated differently than all other parameters; these need to be unified so that subprojects work for all project attributes.

**Comment by vreuter** [comment]
Why should the action to take be "append-to-parent" rather than "replace-parent?" From a user perspective, there doesn't necessarily seem to be one assumption that's obviously more reasonable/intuitive than the other.

**Comment by nsheff** [comment]
I didn't suggest either of those. I think we should just do it the same way we do everything else. I thought that was 'update-parent' (which adds any new ones, overrides any existing)... but anyway, that's not at issue -- in other words, I just don't think the 'constants' section should be treated differently from every other section.

**Comment by vreuter** [comment]
I think difference in nature of the the meaning of the values necessitates differential treatment (what would it mean to "append" something like an output directory or an annotations sheet?)

**Comment by nsheff** [comment]
I don't understand what you're saying, maybe we can talk in person?

**Comment by vreuter** [comment]
Handle also https://github.com/pepkit/peppy/issues/302
