### ISSUE TITLE
Feature request: synonyms section

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#299]
```
synonyms:
  data_source: read1
```

This would take the 'data_source' column (if it exists) and assign its value to an attribute called 'read1'.

This would make it easier to use a single sample annotation sheet across multiple pipelines, that may specify different column names for something.

name ideas:
- synonymical_attributes
- replacement_attributes
- equivalent_attributes
- synonym_attributes
- synonyms
- mapped_attributes
- duplicate_attributes
- matched_attributes
- match_attributes

**Comment by vreuter** [comment]
> ```
> synonyms:
>   data_source: read1
> ```
> 
> This would take the 'data_source' column (if it exists) and assign its value to an attribute called 'read`'.

`read1`?

**Comment by vreuter** [comment]
So we need deeper penetrance than just the annotation sheet, right? Like...you want reference to `read1` and to `data_source` on each of a project's samples to return the same value, rather than simply having the synonym relationship only at the superficial metadata table?

**Comment by nsheff** [comment]
yes, that is correct.

What this would do, is, when it creates the project, it would just copy the 'read1' attribute to 'data_source'. So, both the sample table and the sample objects would have both attributes.

**Comment by nsheff** [comment]
@johanneskoester, @afrendeiro  What do you think of this? Do you have preference for name?

**Comment by afrendeiro** [comment]
This is a good proposal.
I would go with `synonymical_attributes` or `matched_attributes`.

**Comment by johanneskoester** [comment]
`synonyms` sounds best to me.

**Comment by vreuter** [comment]
Sounds like no consensus... @nsheff do you have a decision about naming?

**Comment by nsheff** [comment]
In general I like `synonyms` best. But we just changed `constants` to `constant_attributes` to keep a parallel structure, so the special, sample-modifying sections are now:

- `derived_attributes`
- `implied_attributes`
- `constant_attributes`

So for consistency I think I prefer `synonymical_attributes`... given that it clarifies what this will do (that it relates to sample attributes), this seems to be more clear.

Next question: which direction does it go?

```
synonymical_attributes:
  old: new
```
or
```
synonymical_attributes:
  new: old
```

The former seems to make the most sense to me.

**Comment by vreuter** [comment]
I also like the brevity but slightly prefer the parallelism, and I agree re: the old/new order.

**Comment by nsheff** [comment]
what if we moved all of these 4 things under another heading. So,

```
sample_modifiers:
  constants:
    attribute1: value
    attr2: val2	
  implied:
    organism:
      human:
        imp_attr: value
      mouse:
        imp_arr: val2
  derived: [read1, read2, other_attr]
  synonyms:
    oldattr: newattr
 ```

**Comment by vreuter** [comment]
Sure, that's fine with me.

**Comment by nsheff** [comment]
it's a big change though :)

**Comment by nsheff** [comment]
Let's just go with `synonymical_attributes` for now and we can think about the wholesale changes later.

**Comment by vreuter** [comment]
> Let's just go with `synonymical_attributes` for now and we can think about the wholesale changes later.

So to clarify, a >= 2-step series of changes?
1. Original "synonyms idea," named `synonymical_attributes`
2. Structural changes like the `sample_modifiers` section

**Comment by nsheff** [comment]
yeah, with the second in the category of "maybe it never happens"...
