### ISSUE TITLE
subdir updating when subproject changes output_dir

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/peppy#308]
Currently in case a subproject updates the `metadata.output_dir` of the project the `metadata.results_subdir` and `metadata.submission_subdir` stay the same.

This does not seem right as these strictly depend on the `output_dir` in the first place:

is that expected behavior?

**Comment by nsheff** [comment]
what do you mean by stay the same? typically `results_subdir` and `submission_subdir` should be relative to whatever is in `output_dir` (if they are not absolute).

if output dir changes, I would expect results_subdir not to change (but would now be relative to the new output dir.)

**Comment by michalstolarczyk** [comment]
> what do you mean by stay the same?

do not change, even though the `output_dir` changes

> but would now be relative to the new output dir

this is not happening after the subproject activation:


```
In [4]: p.metadata.output_dir                                                                                                        
Out[4]: '/Users/mstolarczyk/example_caravel'

In [5]: p.metadata.results_subdir                                                                                                    
Out[5]: '/Users/mstolarczyk/example_caravel/results_pipeline'

In [6]: p.activate_subproject("changed_output")                                                                                      
Loading divvy config file: /Users/mstolarczyk/Uczelnia/UVA/code//pepenv/uva_rivanna.yaml
Activating compute package 'default'
Out[6]: 
Project 
...
In [7]: p.metadata.results_subdir                                                                                                    
Out[7]: '/Users/mstolarczyk/example_caravel/results_pipeline'

In [8]: p.metadata.output_dir                                                                                                        
Out[8]: '/Users/mstolarczyk/example_caravel_other'
```

**Comment by michalstolarczyk** [comment]
is the `Project.metadata.results_subdir` gone in favor of `Project.results_folder` after the fix?

**Comment by nsheff** [comment]
it should still be `results_subdir`, as far as I know we didn't change this:

https://pepkit.github.io/docs/project_config/

**Comment by vreuter** [comment]
The specification pattern is still the same as @nsheff noted. I’d expect that old access pattern to work if and only if the key is actually in the metadata section. In other words, there’s no metadata API, so user code access data through metadata should know what was declared, and library code should change to use the higher-level access point (project, not project metadata)

**Comment by vreuter** [comment]
https://github.com/pepkit/peppy/pull/314/commits/ac5fec5bb1f26b35cf767282dff48b6c924c1faa
