### ISSUE TITLE
Produce Sphinx-compatible docs inventory

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/peppy#311]
I'm annotating the type of the parameters of my toolkit's functions with hyperlinks to other documentations and would like to get that to work for `peppy` objects too, but that doesn't seem to work (see for example https://ngs-toolkit.readthedocs.io/en/dev/api.html#ngs_toolkit.analysis.Analysis.from_pep).

It seems the `peppy` docs don't have a `objects.inv` inventory file that Sphinx produces and then queries:
```rst
...
loading intersphinx inventory from http://peppy.databio.org/en/latest/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://peppy.databio.org/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: http://peppy.databio.org/en/latest/objects.inv
...
```

I guess this has to do with the switch to Mkdocs? (https://github.com/pepkit/peppy/issues/239).
I wonder if you know of a way to produce a Sphinx-compatible inventory file from Mkdocs? Judging from the content it probably wouldn't be too hard I guess? (for example: 
`python -m sphinx.ext.intersphinx http://docs.scipy.org/doc/numpy/objects.inv`).

Of course you could also consider switching back to Sphinx ;)

**Comment by nsheff** [comment]
Did you know readthedocs will host either sphinx or mkdocs now? all our docs are hosted at readthedocs, but using mkdocs. so, for example... http://peppy.databio.org/en/latest/

So, you might consider changing to mkdocs :). It gives all the benefits of readthedocs with none of the annoyances of sphinx...writing the documentation in markdown is so much better. I'm fully committed to mkdocs now...

anyway, that `.inv` file is binary file, have you actually looked at the real contents directly? it's not going to be possible to make that by hand really. maybe your question could be raised with the mkdocs project to see if they want to produce such a file... but vanilla mkdocs has no autodocumenting feature like sphinx, so we've written our own at [lucidoc](https://github.com/databio/lucidoc).

**Comment by afrendeiro** [comment]
Yes, you've told me, but I'm not interested in mkdocs.

The inventory file is just a compressed file, nothing more: https://github.com/sphinx-doc/sphinx/blob/d9080b3eef11830c17ed44fd35d22753dce18b34/sphinx/builders/html.py#L830

I guess the bigger issue is the lack of anchor tags in the `mkdocs` produced html.
Maybe if that could be implemented (I guess that's would be a `lucidoc` issue or `mkdocs`?), writing an inventory writer function should be trivial.

**Comment by nsheff** [comment]
anchor tags would probably be easy to add. on what pages do you need them? Just the automatic-generated docs? that's a lucidoc issue and would be easy to solve.

btw, why are you so opposed to mkdocs?

**Comment by afrendeiro** [comment]
Anchor tags would be particularly useful for any class or function that is part of the API, so yes I guess that would be on the side of automatically generated docs.

I'm not opposed to mkdocs, but I'm simply happy with Sphinx. I think it's very feature rich and being widely adopted allows for nice cross-project referencing with most of the Python scientific stack.

**Comment by nsheff** [comment]
@afrendeiro lucidoc 0.4.0 now puts anchors in the API code, can you see if this satisfies your needs?
