### ISSUE TITLE
Ensure Sample's Project ref is merely an attmap, not full Project

### ISSUE THREAD

**Issue by vreuter** [pepkit/peppy#315]

**Comment by nsheff** [comment]
why exactly do we not want it to be a full project?

**Comment by vreuter** [comment]
Cyclic reference create massive problems that have been previously addressed

**Comment by vreuter** [comment]
It's also conceptually bizarre to have it be a full Project. When a sample's created, one of 2 cases is true--it came from a project, or it didn't. If it didn't there's no reference to store. If it did, who/whatever created it already has the project instance.

**Comment by nsheff** [comment]
yep, agreed. i like the attmap rouet.
