### ISSUE TITLE
Cannot correctly format data source (KeyError): 'file_id' -- ../data/{identifier}{file_id}_R1.fq.gz

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#326]
There's a bug in peppy that causes the examples to fail.

Trying to run example 2 from the example_peps:

```
import peppy
p2 = peppy.Project("../examples/example_peps-master/example_subtable2/project_config.yaml")
p2.samples[0].file
```

Returns: 
```
Cannot correctly format data source (KeyError): 'file_id' -- ../data/{identifier}{file_id}_data.txt
Cannot correctly format data source (KeyError): 'file_id' -- ../data/{identifier}{file_id}_data.txt
```

I think it has to do with merging derived columns. Did we mess up the logic in there with some recent update?

This is the main peppy documentation here: http://peppy.databio.org/en/latest/subannotation/

which is broken...

**Comment by nsheff** [comment]
There are also a few other problems with that doc render:

1. the results are not rendered.
2. the examples have changed names.

**Comment by nsheff** [comment]
the warning only shows up in python 3; also, I'm not sure it's actually affecting the functionality...

**Comment by michalstolarczyk** [comment]
I think it's not a bug, but the `file_id` attr is not defined for two of the samples in the example.

I've just added the sample name to the message, so it's more clear
