### ISSUE TITLE
pandas parses empty cols as nan

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#327]
Previously raised several years ago as: https://github.com/pepkit/peppy/issues/159

Then pandas went and deprecated `read_table` and so we had to switch parsing...

https://github.com/pepkit/peppy/issues/276

I think this has re-introduced this bug. I get `--input2 nan` on the command line now for any single-end projects.

**Comment by nsheff** [comment]
example:

```
import peppy
p = peppy.Project("code/ppqc/ppqc_config.yaml")
p.samples[0].read2
```
'nan'

**Comment by nsheff** [comment]
updating pandas solved this problem. I've increased the requirement minimal version.

**Comment by michalstolarczyk** [comment]
Are empty columns not permitted in *sub*sample_tables by design?

I'm asking because `'nan'`s are produced in such case. Empty columns in sample_tables work for me as expected.

**Comment by nsheff** [comment]
No, that would not be by design. I think they should behave the same.
