### ISSUE TITLE
merging is duplicating attributes from the main sample_table

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#328]
in the databio_genomes project, the attributes from the sample table, `genomes.csv`, are getting duplicated, even though they are not defined in the subsample table. I would expect only the subsample attributes to be merged (duplicated).

**Comment by nsheff** [comment]
@michalstolarczyk this turned out to not be solved, right? when we discussed this, I think we didn't add a note somewhere, but has the second issue been addressed?

I believe it was: some attributes were being derived and others were not

**Comment by michalstolarczyk** [comment]
The original issue was resolved, as far as I remember (the duplication was not happening anymore). But we discovered another one:
> some attributes were being derived and others were not

I found the reason: the `derived_attributes` list was being converted to a `set` and we kept losing the order...  the new commit fixes that

**Comment by nsheff** [comment]
excellent
