### ISSUE TITLE
peppy not compatible with divvy==0.5.0

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/peppy#348]
This is likely going to be solved by the PEPv2 release, but for the time being it causes problems when loose requirements are set in tools that e.g. have CI set up.
Please close upon the new release.

**Comment by nsheff** [comment]
the new release is imminent...

**Comment by nsheff** [comment]
pep 2.0 is released, let us know if you run into other problems.

**Comment by afrendeiro** [comment]
Yes thanks, currently testing :D
