### ISSUE TITLE
Multiple subsample tables

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#351]
it would be useful to do:

```
sample_table: assets.csv
subsample_table: [recipe_inputs.csv, genome_descriptions.csv]
```

Right now subsample table has to be just one. They would just be processed individually, adding differnet subsamples, etc.

**Comment by nsheff** [comment]
@stolarczyk is multiple subsample table support finished ?

**Comment by stolarczyk** [comment]
yes, it's ready. I just need to document it

**Comment by nsheff** [comment]
this warrants a change from spec 2.0.0 to 2.1.0, correct?
