### ISSUE TITLE
schema stuff in sample yaml

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#356]
From: https://github.com/pepkit/looper/issues/284

the sample yaml should not include input schema stuff. it should really be a sample yaml.

**Comment by nsheff** [comment]
ok looks great -- 

just thinking though, I still need access to the input schema stuff (like the `files` attribute). but now it's not attached to the sample any long. so, where do you recommend I get it?

I have the filepath in the namespaces via ` pipeline["input_schema"]`. Do I need to parse `pipeline["input_schema"]` again in the plugin to get at the actual list of file attributes? Or is there a better way?  For example, should we attach the parsed input and output schemas to the looper namespaces somehow so the plugins can use them?

**Comment by nsheff** [comment]
used to do this:

```python
 if "files" in sample:
        for file_attr in sample["files"]:
```

can now accommodate with this:

```python

    from eido import read_schema
    s = read_schema(namespaces["pipeline"]["input_schema"])
    print(s[1]["properties"]["samples"]["items"])

    if "files" in s[1]["properties"]["samples"]["items"]:
        for file_attr in s[1]["properties"]["samples"]["items"]["files"]:
```

but there's some other logic that must have been happening to merge these across schemas

**Comment by nsheff** [comment]
Here's a better approach...

```
    files_list = []
    for ischema in read_schema(namespaces["pipeline"]["input_schema"]):
        if "files" in ischema["properties"]["samples"]["items"]:
            files_list.extend(ischema["properties"]["samples"]["items"]["files"])

    for file_attr in files_list:
```

but is there something in eido that handles this schema merging automatically (from imports) so that I don't have to do it here?

**Comment by stolarczyk** [comment]
> but is there something in eido that handles this schema merging automatically (from imports) so that I don't have to do it here?

I don't think so.. It just recursively reads them in and each entry in the resulting list is a separate entity

**Comment by stolarczyk** [comment]
btw, I made a slight change in the cwl plugin, hopefully it doesn't create any conflicts

**Comment by nsheff** [comment]
This is a challenge because these paths are relative,

there's a function in the piface class that handles this: https://github.com/pepkit/looper/blob/ac0645a24b5d9aa18baec76c61adb556d500d2f5/looper/pipeline_interface.py#L55

it would be nice if I could access this processed version somehow, so I don't have to re-process it in the plugin. I don't have access to this function since I don't have a piface object; just it's yaml representation. any ideas?

**Comment by nsheff** [comment]
I was able to solve this one-off like this:

https://github.com/pepkit/looper/commit/5d8194f463613b9faa38aad6bcfcd335ee34a325

but I think there could be a more universal solution.
