### ISSUE TITLE
Inconsistent documentation between code.databio and peppy.databio

### ISSUE THREAD

**Issue by jma1991** [pepkit/peppy#361]
There are a number of inconsistencies with the API documentation between the two websites:

- http://peppy.databio.org/en/latest/autodoc_build/peppy/

- http://code.databio.org/peppy/autodoc_build/peppy/

For example, the code.databio websites seems to define a lot of extra class methods (e.g. get_subsample, set_read_type, set_transcriptome). Additionally, the code for these extra methods are not documented anywhere in the master branch for peppy so I'm not sure how they ended up in the documentation? Anyway, I am currently in the process of converting all of my Snakemake workflows to use peppy, so it would be helpful if you could point me to the correct documentation.

**Comment by nsheff** [comment]
Use http://peppy.databio.org/en/latest/autodoc_build/peppy/

The other one is old (from 2019, take a look in the changelog to see the version that's documented.

Thanks for pointing this out, we're no longer using the code.databio.org server to host docs and so I should just remove it.

**Comment by nsheff** [comment]
I've made the old one point to the new docs now.  Can you tell me how you found the code.databio.org one? did you follow a link from somewhere? I'd like to update the link.

**Comment by jma1991** [comment]
Thanks for the quick reply, I can't actually remember where I got the other link. If I find out, I'll comment again.

**Comment by jma1991** [comment]
Sorry to re-open this issue, but the how-to guides on the website you suggested are all empty?

**Comment by nsheff** [comment]
Indeed, the docs are not building correctly. I will fix it.

**Comment by nsheff** [comment]
Ok refresh; they're all working now except the validate one, which I'm still looking into.

**Comment by nsheff** [comment]
Alright @jma1991 everything should be building again now. Sorry for the inconvenience.

Please keep opening issues if you run into any kind of trouble -- it's really helpful for us. We are excited you're using peppy so let us know if anything's confusing and we'll try to respond quickly.
