### ISSUE TITLE
Get samples based on other column(s)

### ISSUE THREAD

**Issue by arpanda** [pepkit/peppy#363]
Usually, we can get samples based on `sample_name`, In some cases, we want to get samples based on some other column. 

For example, sample table has a column as family_name and I would like to get the samples based on that family. is it possible to do?

**Comment by stolarczyk** [comment]
thanks for reaching out @arpanda

you're right, `Project.get_samples` method does not support sample selection based on columns other than `sample_name`. And yeah, we often select samples based on other properties but didn't feel the need to implement a dedicated method or update the existing one. 

Here's how you can quickly get the samples you need:

```python
x = [s for s in p.samples if s.family_name == "desired_name"]  
```

we might extend the `get_samples` method and add an optional `column` argument to allow that if others think it's useful.

**Comment by arpanda** [comment]
Thanks. This solves my issue. 
In the documentation section, this code example may help the users, if the extended feature is not present.
