### ISSUE TITLE
Avoid pandas.DataFrame.append

### ISSUE THREAD

**Issue by J-Wall** [pepkit/peppy#377]
The `append` method on pandas DataFrames is deprecated (see pandas-dev/pandas#35407). Peppy uses this to build the sample table, leading to verbose `FutureWarning` output from pandas. It's also probably not the most efficient way of making the table.

Instead of appending to an existing DataFrame in `project._get_table_from_samples`, perhaps a python list should be used, and then converted to a DataFrame after the for loop?

**Comment by J-Wall** [comment]
I just realised this was solved in #367. Are there plans to merge and release that soon? Thanks!

**Comment by nsheff** [comment]
Yes I am planning to release later this month

**Comment by J-Wall** [comment]
fixed in v0.32.0

**Comment by Kekananen** [comment]
Do you know if v0.32.0 will be available on conda soon as well?
