### ISSUE TITLE
Instantiate `Project` class from in-memory dict

### ISSUE THREAD

**Issue by nleroy917** [pepkit/peppy#378]
Right now, `peppy`'s API only lets you create a `Project()` from a file that is on disk. It would be nice to have the option to create an instance of `Project()` from a PEP that is already in memory (say, a Python `dict`). 

Right now the `__init__` function looks for a `str` to load the configuration file using `parse_config_file`. It could be nice to have another case where it looks for a `dict` and parses the configuration that way. Maybe something like `parse_config_dict` which is identical to `parse_config_file`, but simply starts with an already loaded `dict`:

```python

    def parse_config_file(self, cfg_path, amendments=None):
        """
        Parse provided yaml config file and check required fields exist.
        :param str cfg_path: path to the config file to read and parse
        :param Iterable[str] amendments: Name of amendments to activate
        :raises KeyError: if config file lacks required section(s)
        """
        if CONFIG_KEY not in self:
            self[CONFIG_KEY] = PathExAttMap()
        if not os.path.exists(cfg_path) and not is_url(cfg_path):
            raise OSError(f"Project config file path does not exist: {cfg_path}")
        config = load_yaml(cfg_path) # <---- parse_config_dict would start here
```

Discussed with @Khoroshevskyi

**Comment by nleroy917** [comment]
Is there a good, reliable way of comparing two instantiated `Project()` classes for checking if they are identical?

**Comment by Khoroshevskyi** [comment]
> Is there a good, reliable way of comparing two instantiated `Project()` classes for checking if they are identical?

1) Try to get all the object variables from two projects and compare them?
2) Try to call some functions from that Project?

**Comment by Khoroshevskyi** [comment]
Fixed
