### ISSUE TITLE
Built-In Method for Comparing two `peppy.Project` classes

### ISSUE THREAD

**Issue by nleroy917** [pepkit/peppy#379]
It would be nice to have a reliable way to compare two project classes. At present, a simple equals operator doesn't work:
```python
import peppy
p1 = peppy.Project("example_peps-cfg2/example_basic/project_config.yaml")
p2 = peppy.Project("example_peps-cfg2/example_basic/project_config.yaml")
p1 == p2
>>> False
```

Maybe comparing the samples and ensuring they are identical in each project class?

This would be useful in tests for #378

**Comment by Khoroshevskyi** [comment]
you should compare all the variables in the object, not just dicts, that were generated by `to_dict()`.
Try to convert object variables using this functin: https://github.com/pepkit/pephub_db/blob/648dfcb6d0dc15d8b758cbffc04839ae6cc303fd/peppy_p.py#L15-L48 and then compare it.

**Comment by nleroy917** [comment]
## Meeting on May 31st, 2022:
- Two PEPs are identical if all their samples are identical
- Two samples are identical if each attribute is identical across the two samples

**Comment by Khoroshevskyi** [comment]
fixed
