### ISSUE TITLE
PEP versions should be assigned by default if one isn't provided

### ISSUE THREAD

**Issue by nleroy917** [pepkit/peppy#382]
`peppy` should provide a default PEP version if one isn't supplied. This would help in two instances:

1. Right now, `peppy` raises an exception if a project is loaded with a configuration file that does not contain a `pep_version` key-value pair.
2. Attempting to access the `pep_version` attribute of a `peppy.Project` instance after installation with just a sample table causes a critical failure.

Assigning a default version (the latest) would gracefully solve both of these problems.

**Comment by Khoroshevskyi** [comment]
fixed!
