### ISSUE TITLE
Performance analysis

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#387]
Peppy works fine for small-ish projects (like, up to thousands of samples), but if you have a huge PEP with tens to hundreds of thousands of samples, it can take prohibitively long to load.

We should do some benchmarking and see if there's any way to improve the performance.

**Comment by rafalstepien** [comment]
![image](https://user-images.githubusercontent.com/43926522/178032815-22de2abd-23d2-4c7a-83d3-ce5e01679598.png)

Most of the time is spent on merging duplicate samples and we should look for optimizations here. This part consists of two list comprehensions which are responsible for almost whole processing time. They are located inside `_auto_merge_duplicated_names` method and I highlighted them in the code snippet below by `# <----- HERE ------` tag:

```
(...)
        for dup in dups_set:
            dup_samples = [s for s in self.samples if getattr(s, self.st_index) == dup]  # <----- HERE ------
            sample_attrs = [
                attr for attr in dup_samples[0].keys() if not attr.startswith("_")
            ]
            merged_attrs = {}
            for attr in sample_attrs:
                merged_attrs[attr] = list(
                    flatten([getattr(s, attr) for s in dup_samples])
                )
            # make single element lists scalars
            for k, v in merged_attrs.items():
                if isinstance(v, list) and len(list(set(v))) == 1:
                    merged_attrs[k] = v[0]
            self._samples = [s for s in self._samples if s[self.st_index] != dup]    # <----- HERE ------
            self.add_samples(Sample(series=merged_attrs))
```

"cumtime" column in the table below shows the total time given method needed to finish. Last column shows the name of given method.
![image](https://user-images.githubusercontent.com/43926522/178033945-c8fac649-b290-4339-b840-00c6e829e502.png)

**Comment by nleroy917** [comment]
For the first line:

```python
dup_samples = [s for s in self.samples if getattr(s, self.st_index) == dup]
```

 it looks like they are just filtering the list down. [`filter()`](https://docs.python.org/3/library/functions.html#filter) is highly optimized.

**Comment by nleroy917** [comment]
If `gettattr` is slow, I believe the `self.st_index` is unchanging (a `str`). Thus, maybe instantiating the index value and using normal dictionary getters would be faster? Something like:

```python
for dup in dups_set:
    st_index = self.st_index
    dup_samples = [s for s in self.samples if s[st_index] == dup]
```

**Comment by rafalstepien** [comment]
I would also think of merging this two list comprehensions into one, because I guess they could do similar things and maybe we don't need to iterate two times here.

**Comment by rafalstepien** [comment]
I will implement optimizations here #388

**Comment by Khoroshevskyi** [comment]
fixed
