### ISSUE TITLE
Optimize peppy code

### ISSUE THREAD

**Issue by rafalstepien** [pepkit/peppy#388]
After #387 there is a possibility to optimize the code so that peppy works better.

**Comment by rafalstepien** [comment]
Performance on current master branch code on my new computer:
![image](https://user-images.githubusercontent.com/43926522/179047031-3343122c-17dd-4143-ba7b-3aec60163b2b.png)

**Comment by rafalstepien** [comment]
Performance after merging two iterations into one:
![image](https://user-images.githubusercontent.com/43926522/179047223-57d036fa-4edd-40cf-88c5-8603e0c4af78.png)

**Comment by Khoroshevskyi** [comment]
fixed

**Comment by xuebingjie1990** [comment]
It still took over 10 min to load the GEO sample table, which has 49176 samples and 12 columns (I killed it at 13 min). It took 5 min to load the ENCODE hg38 sample table, which has 17116 samples and 11 columns.

**Comment by nsheff** [comment]
> It still took over 10 min to load the GEO sample table, which has 49176 samples and 12 columns (I killed it at 13 min). It took 5 min to load the ENCODE hg38 sample table, which has 17116 samples and 11 columns.

OK, this answers the question of "is it fast enough", but another question is, "is it faster?" Can you comment on that?
