### ISSUE TITLE
Remove artifact converters

### ISSUE THREAD

**Issue by rafalstepien** [pepkit/peppy#412]
There was a problem that reading sample_table to CSV sometimes returned in `NaN` values, that eg. @Khoroshevskyi  tried to solve by writing custom converters. I identified the root cause of this problem and introduced fix in https://github.com/pepkit/peppy/pull/409

Now we should go through `peppy` code and check if:
1) this actually solves the issue, if yes then:
2) remove unnecessary artifact functions, methods, converters that aimed to solved that problem, because it is not needed anymore

**Comment by Khoroshevskyi** [comment]
I have checked it, and It looks like everything works fine
