### ISSUE TITLE
Remove logmuse dependency?

### ISSUE THREAD

**Issue by vreuter** [pepkit/peppy#429]
`logmuse` appears to be declared as a dependency, but no longer used? If so, we could remove it from `requirements/requirements-all.txt`

**Comment by nsheff** [comment]
Did peppy ever have CLI? I guess at one point we were toying with that but they we moved that functionality completely to `eido`, so probably `peppy` should never have relied on `logmuse`.

**Comment by vreuter** [comment]
It looks like at one point I added it, but yeah I will remove the dependency now since it looks like the commit where it was introduced was way back and the logging infrastructure is different now.
