### ISSUE TITLE
Imports: documentation unclear

### ISSUE THREAD

**Issue by johnyaku** [pepkit/peppy#434]
I am trying to wrap my head around how imports work. The behaviour does not seem to match my intuitions, or my reading of the documentation.

One or two concrete examples might help clarify this.

Potential examples include:
- importing a YAML file so that one overwrites another
- importing a YAML file to provide _supplementary_ specifications (that don't exist in the other YAML file)
- importing a YAML file to provide _complementay_ specifications (for example, both YAML files include `sample_modifiers` and the resulting merged specification contains elements of both)

Some of these imports may not actually be possible at the moment. But without examples or more detailed explanations it is difficult to understand how this works.

Specifically, I am trying to separate "project config" from "path config" so that arbitrary file naming conventions and directory structures are specified in the latter by way of `sample_modifers` and `derive` specifications but project-level properties are stored in the former.

How can I achieve this?

(My config works if it is all in a single file)

**Comment by nsheff** [comment]
Thank you for raising this issue. I will try to clarify the docs.

First, can you tell me if this example satisfies your use case?

https://github.com/pepkit/example_peps/tree/master/example_imports2

I believe this is demonstrating your third use case.

**Comment by johnyaku** [comment]
This example repo is a gold mine. Thanks for alerting me to it!

Yes, that particular example illustrates the third use case, which is the main one that I'm interested in.
This also gives me a better idea of how the config files are merged.

The docs could probably still do with a few extra sentences to clarify this, but even just linking to these examples would be a huge help.

Thanks again!
