### ISSUE TITLE
should it be easy to create a peppy.Project from a pandas dataframe?

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/peppy#461]

**Comment by khoroshevskyi** [comment]
It is already available from the version 0.34.0

```
peppy.Project().from_pandas(...)
```

**Comment by nsheff** [comment]
https://github.com/pepkit/peppy/issues/443

**Comment by nleroy917** [comment]
I agree that `peppy.Project.from_pandas()` is much more ergonomic.

**Comment by khoroshevskyi** [comment]
This issue was fixed in v0.40.0
