### ISSUE TITLE
reporting results or status to web

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#6]
long-term idea:

we could think about connecting to either a mysql server or to google spreadsheets using [gspread](https://github.com/burnash/gspread), for updating run status, etc.

**Comment by afrendeiro** [comment]
Regardless of the user-facing implementation, we should have functions (in models) that report on the state of each job. Once we have that, building an app to monitor them is easy.

Ideas for that: [Flask](http://flask.pocoo.org/) or [Shiny](http://shiny.rstudio.com/). I'd obviously favor a Python based option, mostly for the interface with the existing platform.

We could have this as a command in looper like described in #4.
Something like: ```$ looper serve``` Output: ```Looper running on localhost, port 4000: http://0.0.0.0:4000/```
Now we have a server constantly updating the status of our jobs.

**Comment by nsheff** [comment]
great idea.

this does require looper to depend on pypiper output though.

**Comment by afrendeiro** [comment]
Just to update this issue (for which I've open the `monitor` branch):

There is a functioning implementation with Flask, which for now simply runs the `summarize` command and displays the summary sheet in a web interface.

Anyone willing to contribute is welcome, but for now it is something low-priority I guess.

**Comment by nsheff** [comment]
This issue became part of looper with the split. It is now part of a looper issue: 

https://github.com/pepkit/looper/issues/30

**Comment by nsheff** [comment]
this has basically been implemented now in [caravel](http://caravel.databio.org)
