### ISSUE TITLE
Submitting to Pypi

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#87]
I Suggest submitting to pypi at version 0.6

**Comment by afrendeiro** [comment]
Will this happen now with 0.7 or you're leaving it for after the models-pep split?

**Comment by vreuter** [comment]
It may make more sense to do it once the models/looper separation is complete, but I think it could definitely be done for this version if we want. It looks like our setup is already close to what's needed for pypi according to [this guide](http://peterdowns.com/posts/first-time-with-pypi.html).
It looks even simpler with the `twine` package as noted in the [Python docs](https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi).

**Comment by nsheff** [comment]
Done. 

https://pypi.org/project/peppy/
