### ISSUE TITLE
implied columns to supplant genome and transcriptome sections

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#96]
I just implemented a new feature called `implied_columns`. This is now active in the `dev` branch and I've added documentation, which you can read here:

http://looper.readthedocs.io/en/dev/implied-columns.html

Implied columns is a generic solution to how we're currently handling `genome` and `transcriptome`. I propose we deprecate these specific sections (which are not documented anywhere anyway) and use the generic `implied_columns` concept.

Looking for feedback from @afrendeiro, @jklughammer, and anyone else who has interest.

**Comment by nsheff** [comment]
See also #94 for code.

**Comment by vreuter** [comment]
This seems to be working well, can this be closed @nsheff ?

**Comment by nsheff** [comment]
The implied columns is great, yeah -- but I guess the remaining question is: can we eliminate the old sections?

Maybe just stick a warning in there if someone specifies a `genomes` or `transcriptomes` section in project_config ?

**Comment by vreuter** [comment]
So you want a requirement for `genomes` or `transcriptomes` to imply a requirement to use `implied_columns`?

**Comment by nsheff** [comment]
No I just mean we deprecate the old use of `genomes`, and provide a warning if someone still uses it, with a suggestion to switch to implied columns.

**Comment by vreuter** [comment]
Ah :ok_hand: sounds good

**Comment by afrendeiro** [comment]
Fine with me on eliminating genomes/transcriptomes from config.
